services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
    depends_on:
      - auth_db

  auth_db:
    image: postgres:15-alpine
    container_name: auth_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  auth_db_data:
